Simplify the upload implementation.
The script was hanging on the rsync to sourceforge, which it hasn't done
that before. I don't know if it's anything to do with running the upload
tasks in the background, but might as well remove the suspicion.

diff --git a/build-docs b/build-docs
--- a/build-docs
+++ b/build-docs
@@ -402,23 +402,11 @@ go()
 
 upload_documentation()
 {
-    pids=""
+    upload_cowic || echo "Upload to cowic failed."
 
     if [ -f $root/upload/upload-trunk ]; then
-        upload_trunk &
-        pids="$pids $!"
+        upload_trunk || echo "Upload trunk docs to sourceforge failed."
     fi
-
-    upload_cowic &
-    pids="$pids $!"
-
-    # Wait for uploads to end
-
-    for pid in $pids
-    do
-        echo "Waiting for $pid"
-        wait $pid || echo "Failed"
-    done
 }
 
 upload_trunk()
