Generalise upload code.
Used to have to do everything differently for uploading to sourceforge,
but now I'm using the boost server for everything.

diff --git a/build-docs b/build-docs
--- a/build-docs
+++ b/build-docs
@@ -467,80 +467,30 @@ upload_documentation()
     upload_cowic || echo "Upload to cowic failed."
 
     if [ -f $root/upload/upload-master ]; then
-        upload_master || echo "Upload master docs failed."
+        upload_to_server master || echo "Upload master docs failed."
     fi
 
     if [ -f $root/upload/upload-develop ]; then
-        upload_develop || echo "Upload develop docs failed."
+        upload_to_server develop || echo "Upload develop docs failed."
     fi
 }
 
-upload_develop()
+upload_to_server()
 {
-    boost_root=$(cat $root/upload/upload-develop)
+    branch=$1
+    boost_root=$(cat $root/upload/upload-$branch)
 
     if [ -d ${boost_root} ]
     then
         if rsync -az --delete-after \
             ${boost_root}/ \
-            dnljms@boost.org:/home/www/shared/archives/live/develop/
+            dnljms@boost.org:/home/www/shared/archives/live/$branch/
         then
-            echo "Uploaded develop to boost server"
-            rm $root/upload/upload-develop
+            echo "Uploaded $branch to boost server"
+            rm $root/upload/upload-$branch
         else
-            echo "Failed to upload develop to boost server"
+            echo "Failed to upload $branch to boost server"
         fi
-    fi
-}
-
-upload_master()
-{
-    boost_root=$(cat $root/upload/upload-master)
-    failed=0
-
-    if [ -d ${boost_root} ]
-    then
-        if rsync -az --delete-after \
-            ${boost_root}/ \
-            dnljms@boost.org:/home/www/shared/archives/live/master/
-        then
-            echo "Uploaded develop to boost server"
-        else
-            echo "Failed to upload develop to boost server"
-        fi
-
-        for library in $UPLOAD_DOCUMENTATION
-        do
-            if rsync -avz --delete-after --delete-excluded \
-                ${boost_root}/libs/$library/ \
-                ${SOURCEFORGE_USERNAME},boost-sandbox@web.sourceforge.net:htdocs/libs/$library/
-            then
-                echo "Uploaded $library."
-            else
-                echo "Failed to upload $library."
-                failed=1
-            fi
-        done
-
-        if rsync -avz --exclude-from $root/exclude.txt --delete-after \
-            ${boost_root}/ \
-            ${SOURCEFORGE_USERNAME},boost-sandbox@web.sourceforge.net:htdocs/
-        then
-            echo "Uploaded combined documentation."
-        else
-            echo "Failed to upload combined documentation."
-            failed=1
-        fi
-
-        if [ $failed = 1 ]
-        then
-            echo "Failed to upload to sourceforge"
-        else
-            rm $root/upload/upload-master
-        fi
-    else
-        echo "Unable to find master to upload."
-        exit 1
     fi
 }
 
